server:
  type: simple
  rootPath: '/api/*'
  applicationContextPath: /
  adminContextPath: /serviceadmin
  connector:
    type: http
    port: 9000

database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./target/example